title: Mind Minutes
description: Less bloggy than a blog, more bloggy than twitter.
github: https://github.com/seblawson11
about: personal website.
author: Seb Lawson
google_analytics: UA-XXXXXXXX-Y
avatar_url: /img/image.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "www.linkedin.com/in/seb-lawson-3b13ab140"
    - icon: fa-github
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/SebLawson11"

share:
  twitter_username: github.io

urls:
    - text: About
      url: /about/
    - text: CV
      url: /CV/

url: "https://seblawson11.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
