title: Mind Minutes
description: Less bloggy than a blog, more bloggy than twitter. An eclectic collection of writings from wherever my curiousity leads me.
author: Mind Minutes
github: https://github.com/seblawson11
about: from SJL
google_analytics: UA-XXXXXXXX-Y
avatar_url:

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "#"
    - icon: fa-github
      link: "#"
    - icon: fa-twitter
      link: "#"

share:
  twitter_username: github.io

urls:
    - text: About
      url: /about/
    - text: Contact
      url: /contact/

url: "https://seblawson11.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
